### ISSUE TITLE
Difficulty in installation

### ISSUE THREAD

**Issue by shruti927** [mediawiki-utilities/python-mediawiki-utilities#41]
While installing mediawiki-utilities I got the following error:
File "C:\Python34\setup.py", line 13, in <module>
    license=open('LICENSE').read(),
FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'

**Comment by halfak** [comment]
Can you paste the full command line that you entered to arrive at that error?

**Comment by shruti927** [comment]
from distutils.core import setup

from setuptools import find_packages

setup(
    name='mediawiki-utilities',
    version="0.4.18",
    author='Aaron Halfaker',
    author_email='aaron.halfaker@gmail.com',
    packages=find_packages(),
    scripts=[],
    url='http://pypi.python.org/pypi/mediawiki-utilities',
    license=open('LICENSE').read(),
    description='A set of utilities for extracting and processing MediaWiki data.',
    long_description=open('README.rst').read(),
    install_requires=[
        "requests>=2.4",
        "pymysql>=0.6.2"],
    test_suite='nose.collector',
    classifiers=[
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3 :: Only",
        "Environment :: Other Environment",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Text Processing :: Linguistic",
        "Topic :: Text Processing :: General",
        "Topic :: Utilities",
        "Topic :: Scientific/Engineering"
    ],
)

I ran this python file and I got the above error.

**Comment by halfak** [comment]
How did you run the file though? 

You should be able to just run "pip install mediawiki-utilities" per the documentation.  

Alternatively, you could `git clone` the repository and then run `python3 setup.py install ...` within the directory.

**Comment by halfak** [comment]
I'm guessing you found the problem.  :)

**Comment by shruti927** [comment]
Yes I did. Thanks for your help :)
