### ISSUE TITLE
html markup in xml

### ISSUE THREAD

**Issue by christophlingg** [mediawiki-utilities/python-mediawiki-utilities#44]
Thanks for providing this great utilities, it helps a lot dealing with bulky xml files!

I bumped into a problem with wikipedia pages that use html markup, like [this file on commons](https://commons.wikimedia.org/wiki/File:%22_ruelle_%22_a_st_jacques_de_la_lande_-_panoramio.jpg).

The `revision.text` does not contain all wiki markup:

> == {{int:filedesc}} ==
{{Information
|description=" ruelle " a st jacques de la lande
|date={{Taken on|2010-11-24}}
|source=http://www.panoramio.com/photo/44141424
|author=[http://www.panoramio.com/user/4219164?with_photo_id=44141424 chisloup]
|permission={{cc-by-3.0|chisloup}}
{{Panoramioreview|Panoramio upload bot|2016-11-19}}
|other_versions=
|other_fields={{Information field|Name=Tags

The text stops when a `<br />` appears in the XML file, html brackets seems to invalid xml and need to be escaped. I can't change the way wikipedia provides their dumps, is there any way I can make your utilities to tolerate those brackets?

Thanks in advance!

**Comment by christophlingg** [comment]
I just found another project: [mwxml](https://github.com/mediawiki-utilities/python-mwxml) Does it make sense to use this project instead?

**Comment by halfak** [comment]
Yes!  I highly recommend mwxml.  Still we shouldn't see a text item partially ignored!  As you have noted, this is invalid XML.  I'll file a task for the XML dumps to be improved.  Thanks for noting the issue!

**Comment by halfak** [comment]
I just checked on the XML dump and it seems to be working correctly for that page.  

From commonswiki-20170601-pages-articles4.xml-p53059063p54559063.bz2:
```
  <page>
    <title>File:&quot; ruelle &quot; a st jacques de la lande - panoramio.jpg</title>
    <ns>6</ns>
    <id>53314454</id>
    <revision>
      <id>221231902</id>
      <parentid>220904302</parentid>
      <timestamp>2016-11-27T10:30:45Z</timestamp>
      <contributor>
        <username>Fab5669</username>
        <id>610900</id>
      </contributor>
      <minor />
      <comment>added [[Category:Streets in Ille-et-Vilaine]] using [[Help:Gadget-HotCat|HotCat]]</comment>
      <model>wikitext</model>
      <format>text/x-wiki</format>
      <text xml:space="preserve">== {{int:filedesc}} ==
{{Information
|description=&quot; ruelle &quot; a st jacques de la lande
|date={{Taken on|2010-11-24}}
|source=http://www.panoramio.com/photo/44141424
|author=[http://www.panoramio.com/user/4219164?with_photo_id=44141424 chisloup]
|permission={{cc-by-3.0|chisloup}}
{{Panoramioreview|Panoramio upload bot|2016-11-19}}
|other_versions=
|other_fields={{Information field|Name=Tags&lt;br /&gt;(from Panoramio photo page)|Value=&lt;code&gt;Saint-Jacques-de-la-Lande&lt;/code&gt;, &lt;code&gt;st jacques de la lande&lt;/code&gt;}}
}}
{{Location|48.081355|-1.715906|source:Panoramio}}

[[Category:Panoramio files uploaded by Panoramio upload bot]]
[[Category:Saint-Jacques-de-la-Lande]]
[[Category:Streets in Ille-et-Vilaine]]</text>
      <sha1>konnca2swh23zf8tbo6cyl9dmymjk5j</sha1>
    </revision>
  </page>
```

**Comment by christophlingg** [comment]
Thank you @halfak for your reply. It took my a while understand that I was mislead: it wasn't the dump file having unescaped characters but me making a mistake at another point.

So both is working correctly, the wikimedia dumps and your library. I am sorry for having bothered you with that, I know your time is better spent on improving the library.

**Comment by halfak** [comment]
No sweat!  I'm glad to have the chance to converse.  Good luck on your analyses :)
